### PR TITLE
Add multiline comment support

### PR DESCRIPTION
**Pull request by SIsilicon**
If comments are found immediately below whatever todo is found, it will show up in the tooltip.
image

### CODE REVIEW

**Comment by OrigamiDev-Pete** [comment]
This is a great idea! I was just reviewing your code and had an idea to take it one step further by creating sub-items in the tree like this: 
Screenshot 2020-12-10 100307

What do you think?

**Comment by SIsilicon** [comment]
Honestly, I don't like how they're arranged in a sub-tree; it's a little awkward to read that way.

**Comment by SIsilicon** [comment]
That's why in the pull request, "..." is appended to indicate multiple lines.

**Comment by OrigamiDev-Pete** [comment]
That's fair. I like your implementation too.
Also, thanks for cleaning up some of my debugging code.

**Pull request merged**
